import { Event } from './event';
import { createReportURL } from './report';
import { log } from './logger';
import { Run } from './run';
import { CompareOutput } from './compare';

export type CreateCommentWithTargetInput = {
  event: Event;
  runId: number;
  sha: string;
  targetRun: Run;
  result: CompareOutput;
  reportUrl: string;
  collectionName: string;
};

export type CreateCommentWithoutTargetInput = {
  event: Event;
  runId: number;
  result: CompareOutput;
  reportUrl: string;
  collectionName: string;
};

const isSuccess = (result: CompareOutput) => {
  return result.failedItems.length === 0 && result.newItems.length === 0 && result.deletedItems.length === 0;
};

const badge = (result: CompareOutput) => {
  return '';
};

export const createCommentWithTarget = ({
  event,
  runId,
  sha: currentHash,
  targetRun,
  result,
  reportUrl,
  collectionName,
}: CreateCommentWithTargetInput): string => {
  const [owner, reponame] = event.repository.full_name.split('/');
  const url = reportUrl;
  log.info(`This report URL is ${url}`);

  const targetHash = targetRun.head_sha;
  const currentHashShort = currentHash.slice(0, 7);
  const targetHashShort = targetHash.slice(0, 7);

  const successOrFailMessage = isSuccess(result)
    ? `${badge(result)}
  
✨✨ That's perfect, there is no visual difference! ✨✨
[FULL REPORT](${url})
    `
    : `${badge(result)}
  
[FULL REPORT](${url})
    `;

  const body = `# 🖼️ Visual Regression Report ${collectionName ? `for ${collectionName}` : ''}

  ${successOrFailMessage}
  
| item    | count                         |
|:--------|:-----------------------------:|
| changed  | ${result.failedItems.length}  |
| added    | ${result.newItems.length}     |
| removed  | ${result.deletedItems.length} |


<sup><sub>This report was generated by comparing [${currentHashShort}](https://github.com/${owner}/${reponame}/commit/${currentHash}) with [${targetHashShort}](https://github.com/${owner}/${reponame}/commit/${targetHash}).
If you would like to check difference, please check [here](https://github.com/${owner}/${reponame}/compare/${targetHashShort}..${currentHashShort}).</sub></sup>

`;

  return body;
};

export const createCommentWithoutTarget = ({
  event,
  runId,
  result,
  reportUrl,
  collectionName,
}: CreateCommentWithoutTargetInput): string => {
  const [owner, reponame] = event.repository.full_name.split('/');
  const url = reportUrl;
  log.info(`This report URL is ${url}`);

  const body = `# 🖼️ Visual Regression Report ${collectionName ? `for ${collectionName}` : ''}
  
  Failed to find a target artifact. All items will be treated as new items and will be used as expected data for the next time.

| item    | count                         |
|:--------|:-----------------------------:|
| added     | ${result.newItems.length}   |

[FULL REPORT](${url})


  `;

  return body;
};
