
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn package
      - uses: superactions/branch-push-action@action
        with:
          branch: action
          files: |
            README.md
            ./action.yml
            ./dist/**/*
            ./report/**/*
            ./template/**/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}