name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn package
      - uses: actions/github-script@v5
        id: target
        with:
          result-encoding: string
          script: |
            return (Math.random() > 0.5) ? "59b7802" : "34f93ed"
      - uses: ./dist
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          image-directory-path: "./images"
          target-hash: "${{ steps.target.outputs.result }}"
